### ISSUE TITLE
Error: void-function (cl-defmacro)

### ISSUE THREAD

**Issue by csantosb** [gmlarumbe/fpga#2]
`cl-defmacro` is provided by `cl-macs `library, so you need to [(provide 'cl-macs)](url). Right ?

**Comment by gmlarumbe** [comment]
Hi @csantosb ,

Thanks for reporting the issue. 

The error also showed up in the melpazoid GitHub workflow and seems to be fixed after commit a244912.

Could you check if it works for you as well?

Thanks!

**Comment by csantosb** [comment]
Fixed, thanks !
